@URL = http://localhost:55555/api

###

GET {{URL}}/prices
Content-Type: application/json

###

GET {{URL}}/prices/1
Content-Type: application/json

###
POST {{URL}}/prices
Content-Type: application/json

{
  "id": 0,
  "priceValue": 15,
  "currency": "PLN"
}

###

PUT {{URL}}/prices/1
Content-Type: application/json

{
  "id": 1,
  "priceValue": 369,
  "currency": "PLN"
}

###

DELETE {{URL}}/prices/1